ALTER TABLE drives
    ADD COLUMN IF NOT EXISTS avg_speed_kmh DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS min_speed_kmh DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS max_speed_kmh DOUBLE PRECISION;
